### ISSUE TITLE
The userscript is not working

### ISSUE THREAD

**Issue by csf30816** [Mega-Mewthree/Moomoo-AI-Bot-Sender#23]
I can not see my id and so the useful commands are not available. Possibly add a feature to make leader default commander. Thanks, keep up the great work!

I might join you guys (again)

I am using FireFox Developer Edition latest with Tampermonkey on Windows 10 PC

**Comment by Mega-Mewthree** [comment]
Please screenshot your moomoo screen after spawning and post it here.

**Comment by csf30816** [comment]
Hello,
You respond fast! Here is a screenshot I took. Could it possibly be that I am using a VPN? 
![image](https://user-images.githubusercontent.com/18520232/38158875-6e7557e6-3438-11e8-9818-773a6d47fb60.png)

**Comment by csf30816** [comment]
Actually thinking about it it probably is because I am using a VPN since it sends it over localhost.

**Comment by csf30816** [comment]
Any updates on this?

**Comment by Mega-Mewthree** [comment]
Is the script ON for the page?

**Comment by csf30816** [comment]
Yes. It was the VPN and using my Public IP did not work so I just disabled my VPN now I can get banned from Moomoo ;)
