### ISSUE TITLE
Discord invite expired

### ISSUE THREAD

**Issue by csf30816** [Mega-Mewthree/Moomoo-AI-Bot-Sender#24]
The Discord Invite link in the description has expired.

**Comment by Mega-Mewthree** [comment]
It's on lockdown.

**Comment by csf30816** [comment]
Ah, was somebody leaking information or is this information classified?

**Comment by csf30816** [comment]
These are the days I wish I hadn't left the server :)

**Comment by Mega-Mewthree** [comment]
Put the new link up.

**Comment by haykam821** [comment]
Fixed by commit afd3856589f6.
